---
# tasks file for while_true_do.rpo_epel

- name: Include distribution Vars
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
  tags:
    - epel
    - package
    - repository
    - system

- name: Include distribution Tasks
  include_tasks: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
  tags:
    - epel
    - package
    - repository
    - system
    - testing
