---
# tasks file for while_true_do.rpo_epel

- name: Manage EPEL Packages
  yum:
    name: "{{ wtd_rpo_epel_package }}"
    state: "{{ wtd_rpo_epel_package_state }}"
  become: true
  tags:
    - epel
    - package
    - repository
    - system

- name: Manage EPEL Repository
  ini_file:
    path: "/etc/yum.repos.d/epel.repo"
    section: "epel"
    option: "enabled"
    value: "{{ wtd_rpo_epel_conf_enabled }}"
    no_extra_spaces: true
  become: true
  when:
    - wtd_rpo_epel_package_state != "absent"
  tags:
    - epel
    - package
    - repository
    - system

- name: Manage EPEL Testing Repository
  ini_file:
    path: "/etc/yum.repos.d/epel-testing.repo"
    section: "epel-testing"
    option: "enabled"
    value: "{{ wtd_rpo_epel_conf_testing_enabled }}"
    no_extra_spaces: true
  become: true
  when:
    - wtd_rpo_epel_package_state != "absent"
  tags:
    - epel
    - package
    - repository
    - system
    - testing
